[package]
name = "ndas-cli"
version = "0.1.0"
authors = ["Aditya Kresna <aditya.kresna@outlook.co.id>"]
edition = "2018"

[build-dependencies]
bindgen = "0.55.1"

[dependencies]
signal-hook = "0.1.16"
crossbeam-channel = "0.4.4"
